### ISSUE TITLE
300ep_uhd_c6_best.pt and drone_video2.MP4

### ISSUE THREAD

**Issue by byq-luo** [metabuild-radarAI/crossroad_TrafficCount#1]
Can you send me these two attachments（300ep_uhd_c6_best.pt and drone_video2.MP4）, thank you. luozhongbin2015@gmail.com

**Comment by jdkim4444** [comment]
I update both file.

**Comment by metabuild-radarAI** [comment]
I update both file. Thanks for your attention.
